on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
        shell: bash  
      - uses: actions/checkout@v3
      - id: foo
        uses: actions/helloshell@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
